import { ButtonProps, ContentWrapperProps, HeaderProps, WrapperHeaderProps, WrapperProps } from "./styled.types";
export declare const defaultMinWidth = 400;
export declare const defaultMinHeight = 225;
export declare const rightResizeCursor = "ew-resize";
export declare const bottomResizeCursor = "ns-resize";
export declare const bottomRightResizeCursor = "nwse-resize";
export declare const Container: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const Wrapper: import("styled-components").StyledComponent<"div", any, WrapperProps, never>;
export declare const WrapperHeader: import("styled-components").StyledComponent<"div", any, WrapperHeaderProps, never>;
export declare const WindowHeader: import("styled-components").StyledComponent<"div", any, HeaderProps, never>;
export declare const ContentWrapper: import("styled-components").StyledComponent<"div", any, ContentWrapperProps, never>;
export declare const WindowTitle: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const RightResizeHandle: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const BottomResizeHandle: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const BottomRightResizeHandle: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const Button: import("styled-components").StyledComponent<"button", any, ButtonProps, never>;
export declare const Icons: import("styled-components").StyledComponent<"span", any, {}, never>;
export declare const CloseIcon: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const FullscreenIcon: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const MinIcon: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const CloseIconBootstrap: import("styled-components").StyledComponent<import("@styled-icons/styled-icon").StyledIcon, any, {}, never>;
export declare const MinIconBootstrap: import("styled-components").StyledComponent<import("@styled-icons/styled-icon").StyledIcon, any, {}, never>;
export declare const MaxiIconBootstrap: import("styled-components").StyledComponent<import("@styled-icons/styled-icon").StyledIcon, any, {}, never>;
export declare const SunIcon: import("styled-components").StyledComponent<import("@styled-icons/styled-icon").StyledIcon, any, {}, never>;
export declare const MoonIcon: import("styled-components").StyledComponent<import("@styled-icons/styled-icon").StyledIcon, any, {}, never>;
